// archive/react-v1/components/SettingsModal.tsx

import React, { useState, useEffect } from 'react';
import { X, Settings, Check } from 'lucide-react';
import { AISettings, AIProvider } from '../types';
import { getAISettings, saveAISettings } from '../services/storage';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose }) => {
  const [settings, setSettings] = useState<AISettings>({
    provider: 'gemini',
    apiKey: '',
    baseUrl: '',
    modelName: ''
  });
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setSettings(getAISettings());
    }
  }, [isOpen]);

  const handleSave = () => {
    saveAISettings(settings);
    setSaved(true);
    setTimeout(() => {
        setSaved(false);
        onClose();
    }, 1000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-xl shadow-2xl max-w-md w-full overflow-hidden border border-stone-100">
        <div className="p-6">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-bold font-serif flex items-center gap-2 text-gray-800">
              <Settings size={20} className="text-gray-600" />
              AI 设置
            </h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X size={20} />
            </button>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">API 提供商</label>
              <div className="flex gap-2 bg-stone-100 p-1 rounded-lg">
                <button
                  onClick={() => setSettings({ ...settings, provider: 'gemini' })}
                  className={`flex-1 py-1.5 text-sm font-medium rounded-md transition-all ${
                    settings.provider === 'gemini' 
                    ? 'bg-white text-indigo-600 shadow-sm ring-1 ring-black/5' 
                    : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  Google Gemini
                </button>
                <button
                  onClick={() => setSettings({ ...settings, provider: 'openai' })}
                  className={`flex-1 py-1.5 text-sm font-medium rounded-md transition-all ${
                    settings.provider === 'openai' 
                    ? 'bg-white text-green-600 shadow-sm ring-1 ring-black/5' 
                    : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  OpenAI / Custom
                </button>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                API Key
                <span className="text-xs text-gray-400 font-normal ml-2">
                    {settings.provider === 'gemini' && !settings.apiKey ? '(使用默认环境变量)' : ''}
                </span>
              </label>
              <input
                type="password"
                value={settings.apiKey}
                onChange={(e) => setSettings({ ...settings, apiKey: e.target.value })}
                placeholder="sk-..."
                className="w-full px-3 py-2.5 bg-stone-50 text-gray-900 border border-stone-300 rounded-lg focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500 transition-all placeholder-gray-400"
              />
            </div>

            {settings.provider === 'openai' && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">API Base URL</label>
                <input
                  type="text"
                  value={settings.baseUrl}
                  onChange={(e) => setSettings({ ...settings, baseUrl: e.target.value })}
                  placeholder="https://api.openai.com/v1"
                  className="w-full px-3 py-2.5 bg-stone-50 text-gray-900 border border-stone-300 rounded-lg focus:bg-white focus:outline-none focus:ring-2 focus:ring-green-500/50 focus:border-green-500 transition-all placeholder-gray-400"
                />
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">模型名称 (Model)</label>
              <input
                type="text"
                value={settings.modelName}
                onChange={(e) => setSettings({ ...settings, modelName: e.target.value })}
                placeholder={settings.provider === 'gemini' ? 'gemini-2.5-flash' : 'gpt-4o-mini'}
                className="w-full px-3 py-2.5 bg-stone-50 text-gray-900 border border-stone-300 rounded-lg focus:bg-white focus:outline-none focus:ring-2 focus:ring-stone-200 focus:border-stone-400 transition-all placeholder-gray-400"
              />
            </div>
          </div>

          <div className="mt-8">
            <button
              onClick={handleSave}
              className={`w-full py-2.5 rounded-lg font-medium text-white flex items-center justify-center gap-2 transition-all shadow-md active:scale-[0.98] ${
                 saved ? 'bg-green-600' : 'bg-ink hover:bg-gray-800'
              }`}
            >
              {saved ? <Check size={18} /> : null}
              {saved ? '已保存' : '保存设置'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

// frontend-vue/src/components/SettingsModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X, Save } from 'lucide-vue-next';
import { getAISettings, saveAISettings } from '@/services/storage';
import type { AISettings, AIProvider } from '@/types';

const props = defineProps<{
  isOpen: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const settings = ref<AISettings>(getAISettings());

const handleSave = () => {
  saveAISettings(settings.value);
  emit('close');
  // Reload page to apply settings? Or just let services read from storage.
  // Services read from storage on every call, so it's fine.
};
</script>

<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-fade-in">
    <div class="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 m-4 text-ink">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-xl font-bold font-serif text-gray-900">设置</h2>
        <button @click="emit('close')" class="text-gray-400 hover:text-gray-600">
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="space-y-6">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">
            AI 提供商
          </label>
          <div class="flex gap-4">
            <label class="flex items-center gap-2 cursor-pointer">
              <input 
                type="radio" 
                v-model="settings.provider" 
                value="gemini"
                class="text-blue-600 focus:ring-blue-500"
              />
              <span class="text-gray-800">Google Gemini</span>
            </label>
            <label class="flex items-center gap-2 cursor-pointer">
              <input 
                type="radio" 
                v-model="settings.provider" 
                value="openai"
                class="text-blue-600 focus:ring-blue-500"
              />
              <span class="text-gray-800">OpenAI Compatible</span>
            </label>
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">
            API Key
          </label>
          <input 
            v-model="settings.apiKey"
            type="password"
            placeholder="sk-..."
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all bg-white text-gray-900"
          />
          <p class="text-xs text-gray-500 mt-1">
            Key 仅存储在本地浏览器中，不会上传到服务器。
          </p>
        </div>

        <div v-if="settings.provider === 'openai'">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            Base URL (可选)
          </label>
          <input 
            v-model="settings.baseUrl"
            type="text"
            placeholder="https://api.openai.com/v1"
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all bg-white text-gray-900"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">
            模型名称
          </label>
          <input 
            v-model="settings.modelName"
            type="text"
            placeholder="gemini-2.5-flash / gpt-4o"
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all bg-white text-gray-900"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">
            幽灵文字生成延迟 ({{ settings.ghostDelay || 1000 }}ms)
          </label>
          <input 
            v-model.number="settings.ghostDelay"
            type="range"
            min="500"
            max="5000"
            step="100"
            class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
          />
          <div class="flex justify-between text-xs text-gray-500 mt-1">
            <span>快 (0.5s)</span>
            <span>慢 (5s)</span>
          </div>
        </div>
      </div>

      <div class="mt-8 flex justify-end">
        <button 
          @click="handleSave"
          class="flex items-center gap-2 px-6 py-2 bg-gray-900 text-white rounded-full hover:bg-gray-800 transition-colors"
        >
          <Save class="w-4 h-4" />
          保存设置
        </button>
      </div>
    </div>
  </div>
</template>
